export enum DamageStatus {
  REGISTRADA = 'REGISTRADA',
  SUGESTAO_PENDENTE = 'SUGESTAO_PENDENTE',
  ACAO_DEFINIDA = 'ACAO_DEFINIDA',
  EM_REPOSICAO = 'EM_REPOSICAO',
  CANCELAMENTO_APLICADO = 'CANCELAMENTO_APLICADO',
  RESOLVIDA = 'RESOLVIDA',
}
