export enum OrderOperationalStatus {
  PENDENTE = 'PENDENTE',
  PARCIALMENTE_ENTREGUE = 'PARCIALMENTE_ENTREGUE',
  ENTREGUE = 'ENTREGUE',
  ATRASADO = 'ATRASADO',
  DIVERGENCIA = 'DIVERGENCIA',
  EM_AVARIA = 'EM_AVARIA',
  REPOSICAO = 'REPOSICAO',
  CANCELADO = 'CANCELADO',
}
