export enum QuotationStatus {
  EM_NEGOCIACAO = 'EM_NEGOCIACAO',
  AGUARDANDO_RESPOSTA = 'AGUARDANDO_RESPOSTA',
  AGUARDANDO_REVISAO = 'AGUARDANDO_REVISAO',
  APROVADA = 'APROVADA',
  REPROVADA = 'REPROVADA',
  CORRECAO_SOLICITADA = 'CORRECAO_SOLICITADA',
  AGUARDANDO_REENVIO_SIENGE = 'AGUARDANDO_REENVIO_SIENGE',
  INTEGRADA_SIENGE = 'INTEGRADA_SIENGE',
  SEM_RESPOSTA = 'SEM_RESPOSTA',
  FORNECEDOR_FECHADO = 'FORNECEDOR_FECHADO',
  FORNECEDOR_INVALIDO_MAPA = 'FORNECEDOR_INVALIDO_MAPA',
  ENCERRADA = 'ENCERRADA',
}
