/**
 * Webhook types consumed from Sienge.
 * PRD-07 §9.2
 */
export enum WebhookType {
  PURCHASE_ORDER_GENERATED_FROM_NEGOCIATION = 'PURCHASE_ORDER_GENERATED_FROM_NEGOCIATION',
  PURCHASE_QUOTATION_NEGOTIATION_AUTHORIZATION_CHANGED = 'PURCHASE_QUOTATION_NEGOTIATION_AUTHORIZATION_CHANGED',
  PURCHASE_ORDER_AUTHORIZATION_CHANGED = 'PURCHASE_ORDER_AUTHORIZATION_CHANGED',
  PURCHASE_ORDER_ITEM_MODIFIED = 'PURCHASE_ORDER_ITEM_MODIFIED',
  PURCHASE_ORDER_FINANCIAL_FORECAST_UPDATED = 'PURCHASE_ORDER_FINANCIAL_FORECAST_UPDATED',
  CONTRACT_AUTHORIZED = 'CONTRACT_AUTHORIZED',
  CONTRACT_UNAUTHORIZED = 'CONTRACT_UNAUTHORIZED',
  MEASUREMENT_AUTHORIZED = 'MEASUREMENT_AUTHORIZED',
  MEASUREMENT_UNAUTHORIZED = 'MEASUREMENT_UNAUTHORIZED',
  CLEARING_FINISHED = 'CLEARING_FINISHED',
  CLEARING_DELETED = 'CLEARING_DELETED',
}

/**
 * Webhook processing status.
 * PRD-07 §4.3
 */
export enum WebhookStatus {
  RECEIVED = 'received',
  PROCESSING = 'processing',
  PROCESSED = 'processed',
  FAILED = 'failed',
}
