apiVersion: v1
kind: Service
metadata:
  name: projetog-workers
  namespace: projetog
spec:
  selector:
    app: projetog-workers
  ports:
    - name: metrics
      port: 9080
      targetPort: metrics
